const suggestions=['Best laptops for developers','Plan a 5 day trip to Japan','Compare MacBook Air vs Dell XPS','Best AI tools for startups','How to start a clothing brand','Find investment opportunities'];
const sources=[['CNBC','News','Best laptops for developers in 2026',94],['The Verge','Web','MacBook Air M3 review',91],['Reddit /r/devops','Reddit','What do developers use every day?',83],['YouTube','Video','Best laptops for coding',81],['Wirecutter','Web','Top picks for programmers',89]];
let state={tab:'search',screen:'home',query:'',result:buildResult('Plan a 5 day trip to Japan'),saved:JSON.parse(localStorage.getItem('sail7.saved')||'[]'),messages:['Alex: I added some places for Day 2, check out the itinerary?','Maya: Looks amazing! Can we add a food tour in Osaka?','You: Good call. I’ll update the plan.']};
function buildResult(query){const travel=/japan|trip|travel|ski|itinerary/i.test(query),compare=/compare|vs|macbook|dell/i.test(query);return{query,summary:travel?'Sail7 analyzed current travel guidance, sample itineraries, seasonal advice, and budget data to create a balanced plan with culture, food, and low-friction logistics.':compare?'Sail7 compared specifications, expert reviews, buyer feedback, and pricing to produce a practical recommendation based on performance, battery life, portability, and value.':'Sail7 synthesized trusted web, news, community, and video sources into a concise answer with source-backed takeaways and next steps.',highlights:travel?['Tokyo — modern culture and iconic food','Kyoto — temples, tea houses, and gardens','Osaka — nightlife and street food','Mount Fuji — scenic day trip option']:['Clear winner selected by weighted scoring','Trade-offs shown across cost, quality, and fit','Source list retained for verification','Saved to your workspace automatically'],facts:travel?[['Estimated Cost','$1,650 per person'],['Best Time to Go','Mar – May'],['Trip Length','5 days'],['Confidence','92%']]:[['Top Pick','MacBook Air M3'],['Best Value','Dell XPS 13'],['Sources','120+'],['Confidence','88%']],itinerary:[['8:30 AM',travel?'Arrive in Tokyo':'Define decision criteria',travel?'Narita Airport arrival and transit':'Confirm budget and constraints',0],['10:00 AM',travel?'Shibuya Crossing':'Review expert sources',travel?'Explore the crossing and nearby cafés':'Read reviews and benchmark data',15],['1:00 PM',travel?'Lunch in Shibuya':'Compare finalists',travel?'Top-rated local restaurants':'Score options side by side',28],['3:00 PM',travel?'Sensō-ji Temple':'Validate with user reviews',travel?'Historic temple in Asakusa':'Check reliability and owner sentiment',8],['7:00 PM',travel?'Dinner in Shinjuku':'Finalize recommendation',travel?'Omoide Yokocho food walk':'Save final report and citations',52]],sources};}
function icon(x){return `<span class="ico">${x}</span>`}function set(p){Object.assign(state,p);render()}function runSearch(q=state.query){if(!q.trim())return;state.query=q.trim();state.result=buildResult(state.query);state.screen='research';render();setTimeout(()=>set({screen:/compare|vs|macbook|dell/i.test(q)?'compare':'result'}),850)}
function save(){state.saved=[state.result,...state.saved.filter(s=>s.query!==state.result.query)].slice(0,8);localStorage.setItem('sail7.saved',JSON.stringify(state.saved));set({tab:'workspace',screen:'home'})}
function render(){const r=state.result,total=r.itinerary.reduce((a,x)=>a+x[3],320);document.querySelector('#app').innerHTML=`<div class="shell"><aside><div class="brand"><div class="sail">◢</div><h1>Sail7</h1></div><p>AI Search. Deep Answers.<br><b>Built Together.</b></p>${['✦ AI-Powered Search','⌕ Deep Research','▣ Real-Time Sources','♧ Group Collaboration','↗ Share & Build','▤ Your AI Workspace'].map(f=>`<div class="feature">${f}</div>`).join('')}</aside><main class="phone"><header><span>9:41</span><b>${state.screen==='home'?'Sail7':state.screen[0].toUpperCase()+state.screen.slice(1)}</b><button onclick="set({screen:'sources'})">☰</button></header>${state.screen!=='home'?`<button class="back" onclick="set({screen:'home'})">‹ Back</button>`:''}${screenHtml(r,total)}<nav>${[['search','⌂'],['workspace','▣'],['spaces','＋'],['profile','♙']].map(([t,i])=>`<button class="${state.tab===t?'active':''}" onclick="nav('${t}')">${i}<small>${t}</small></button>`).join('')}</nav></main></div>`}
function screenHtml(r,total){if(state.screen==='home')return `<section class="home"><h2>What do you want to <b>figure out?</b></h2><form class="searchbox" onsubmit="event.preventDefault();runSearch(document.querySelector('#q').value)">${icon('⌕')}<input id="q" value="${state.query}" oninput="state.query=this.value" placeholder="Ask anything..."><button>➜</button></form><p>Try searching</p><div class="grid">${suggestions.map(s=>`<button onclick="runSearch('${s.replaceAll("'","\\'")}')">${icon('✦')}${s}</button>`).join('')}</div>${state.tab==='workspace'?`<div class="card"><h3>Saved Workspace</h3>${state.saved.length?state.saved.map(s=>`<button class="row" onclick="state.result=buildResult('${s.query.replaceAll("'","\\'")}');set({screen:'result'})">${s.query}<b>➜</b></button>`).join(''):'No saved reports yet.'}</div>`:''}</section>`;
if(state.screen==='research')return `<section class="center"><h2>Deep Research</h2><b>Researching...</b>${['Analyzing 120+ sources','Reading reviews','Comparing prices','Fact checking','Summarizing findings'].map(x=>`<p class="check">✓ ${x}</p>`).join('')}<div class="orb"></div><button onclick="set({screen:'home'})">Cancel Research</button></section>`;
if(state.screen==='result')return `<section><h2>${r.query}</h2><div class="tabs"><button>Overview</button><button onclick="set({screen:'itinerary'})">Itinerary</button><button>Budget</button><button onclick="set({screen:'sources'})">Sources</button></div><div class="card"><h3>🤖 Sail7 Summary</h3><p>${r.summary}</p><h3>Top Highlights</h3>${r.highlights.map(h=>`<p class="check">✓ ${h}</p>`).join('')}</div><div class="hero"></div><div class="facts">${r.facts.map(([k,v])=>`<div><small>${k}</small><b>${v}</b></div>`).join('')}</div><button class="primary" onclick="save()">Save & Share</button></section>`;
if(state.screen==='itinerary')return `<section><h2>Itinerary</h2>${r.itinerary.map((i,n)=>`<div class="timeline"><span>${i[0]}</span><i></i>${n<r.itinerary.length-1?'<em></em>':''}<div><b>${i[1]}</b><p>${i[2]}</p></div></div>`).join('')}<div class="card row"><b>Total Est. Cost</b><h2>$${total}</h2></div></section>`;
if(state.screen==='compare')return `<section><h2>Compare</h2><div class="compare"><div><div class="laptop"></div>MacBook Air M3<br><b>$1,099</b></div><b>VS</b><div><div class="laptop two"></div>Dell XPS 13<br><b>$999</b></div></div><div class="score"><b>4.8</b><span>Sail7 Score</span><b>4.4</b></div>${['Performance','Battery Life','Display','Portability','Value'].map((x,i)=>`<div class="row"><b>${(4.9-i/10).toFixed(1)}</b>${x}<b>${(4.3+i/10).toFixed(1)}</b></div>`).join('')}<div class="winner">🏆 Winner: MacBook Air M3<br><small>Best all-around for most people.</small></div></section>`;
if(state.screen==='sources')return `<section><h2>Sources</h2><div class="tabs"><button>All</button><button>Web</button><button>News</button><button>Reddit</button></div>${r.sources.map((s,i)=>`<div class="source"><b>${i+1}</b><div><small>${s[0]} · ${s[1]} · ${s[3]}% match</small><p>${s[2]}</p></div></div>`).join('')}<button class="primary">View All 120 Sources</button></section>`;
if(state.screen==='chat')return `<section><h2>Japan Trip Planning</h2>${state.messages.map((m,i)=>`<p class="bubble ${i===2?'me':''}">${m}</p>`).join('')}<form class="chat" onsubmit="event.preventDefault();const v=this.msg.value;if(v){state.messages.push('You: '+v);this.msg.value='';render()}"><input name="msg" placeholder="Message your group..."><button>➤</button></form></section>`;
return `<section class="center"><h2>👑 Unlock Premium</h2><p>Unlimited searches, deeper research, AI workspaces, file uploads, and priority support.</p><button class="primary">$4.99 / month · Continue</button></section>`}
function nav(t){state.tab=t;state.screen=t==='spaces'?'chat':t==='profile'?'paywall':'home';render()}window.set=set;window.runSearch=runSearch;window.save=save;window.nav=nav;render();
